name: Setup Rust
description: Setup Rust toolchain, cache, and install cargo-binstall

inputs:
  binstall:
    description: Install cargo-binstall
    required: false
  targets:
    description: Targets to install
    required: false
  components:
    description: Components to install
    required: false
  stage:
    description: Stage of the action
    required: true
    type: choice
    options:
      - test
      - build
      - publish

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Cache Cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ inputs.stage }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo-binstall
      if: ${{ inputs.binstall }}
      uses: taiki-e/install-action@v2
      with:
        tool: ${{ inputs.binstall }}