name: Publish to npm

inputs:
  working_directory:
    description: Directory containing package.json
    required: true
  npm_token:
    description: NPM token
    required: true
  github_token:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v5

    - name: Publish
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        npm publish --access public --provenance
      env:
        NPM_TOKEN: ${{ inputs.npm_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
