// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a color in various formats with support for RGB, RGBA, and integer RGB values.
 *
 * The enum supports three color formats:
 * - `Rgb`: RGB color with 8-bit components (r, g, b)
 * - `Rgba`: RGBA color with 8-bit RGB components and 32-bit float alpha (r, g, b, a)
 * - `RgbInt`: Single 32-bit integer containing RGB values
 */
export type Color = [number, number, number] | [number, number, number, number] | number;
