// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the direction of flex items within a flex container.
 *
 * This enum determines how flex items are laid out along the main axis.
 */
export type FlexDirection = "row" | "column" | "row_reverse" | "column_reverse";
