// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents spacing between flex items.
 *
 * Can be either a single value applied to both axes, or separate values
 * for horizontal and vertical spacing.
 */
export type Gap = number | [number, number];
