// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInput } from "./ColorInput";
import type { FontWeight } from "./FontWeight";
import type { SidesValue } from "./SidesValue";
import type { TextAlign } from "./TextAlign";
import type { ValuePercentageAuto } from "./ValuePercentageAuto";

/**
 * Style properties that can be inherited by child elements.
 *
 * These properties are typically passed down from parent to child elements
 * in the layout hierarchy, such as font settings and colors.
 */
export type InheritableStyle = { 
/**
 * Color of the element's border
 */
border_color?: ColorInput, 
/**
 * Text color for child text elements
 */
color?: ColorInput, 
/**
 * Font size in pixels for text rendering
 */
font_size?: number, 
/**
 * Font family name for text rendering
 */
font_family?: string, 
/**
 * Line height multiplier for text spacing
 */
line_height?: number, 
/**
 * Font weight for text rendering
 */
font_weight?: FontWeight, 
/**
 * Maximum number of lines for text before truncation
 */
max_lines?: number, 
/**
 * Corner radius for rounded borders in pixels
 */
border_radius?: SidesValue<ValuePercentageAuto>, 
/**
 * Text alignment within the element
 */
text_align?: TextAlign, };
