// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text alignment options for text rendering.
 *
 * Corresponds to CSS text-align property values.
 */
export type TextAlign = "left" | "right" | "center" | "justify" | "end";
