// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how flex items are aligned along the cross axis.
 *
 * This enum determines how items are aligned within the flex container
 * along the cross axis (perpendicular to the main axis).
 */
export type AlignItems =
  | "start"
  | "end"
  | "flex-start"
  | "flex-end"
  | "center"
  | "baseline"
  | "stretch";
