// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionComponent } from "./PositionComponent";

/**
 * Parsed `background-position` value for one layer.
 */
export type BackgroundPosition = { 
/**
 * X-axis position component.
 */
x: PositionComponent, 
/**
 * Y-axis position component.
 */
y: PositionComponent, };
