// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Parsed `background-size` for one layer.
 */
export type BackgroundSize = "cover" | "contain" | { 
/**
 * Width value for the background image.
 */
width: LengthUnit, 
/**
 * Height value for the background image.
 */
height: LengthUnit, };
