// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundPosition } from "./BackgroundPosition";

/**
 * A list of `background-position` values (one per layer).
 */
export type BackgroundPositions = Array<BackgroundPosition> | string;
