// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-axis repeat style.
 */
export type BackgroundRepeatStyle = "repeat" | "no-repeat" | "space" | "round";
