// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundImage } from "./BackgroundImage";

/**
 * A collection of background images.
 */
export type BackgroundImages = Array<BackgroundImage> | string;
