// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundRepeat } from "./BackgroundRepeat";

/**
 * A list of background-repeat values (layered).
 */
export type BackgroundRepeats = Array<BackgroundRepeat> | string;
