// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackgroundSize } from "./BackgroundSize";

/**
 * A list of `background-size` values (one per layer).
 */
export type BackgroundSizes = Array<BackgroundSize> | string;
