// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinearGradient } from "./LinearGradient";
import type { RadialGradient } from "./RadialGradient";

/**
 * Background image variants supported by Takumi.
 */
export type BackgroundImage = LinearGradient | RadialGradient;
