// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorInput } from "./ColorInput";
import type { LengthUnit } from "./LengthUnit";

/**
 * Defines a box shadow for an element.
 *
 * This struct contains the properties for a box shadow, including color,
 * offset, blur radius, spread radius, and inset flag.
 */
export type BoxShadow = { 
/**
 * Color of the box shadow
 */
color: ColorInput, 
/**
 * Horizontal offset of the box shadow
 */
offset_x: LengthUnit, 
/**
 * Vertical offset of the box shadow
 */
offset_y: LengthUnit, 
/**
 * Blur radius of the box shadow (must be non-negative)
 */
blur_radius: LengthUnit, 
/**
 * Spread radius of the box shadow
 */
spread_radius: LengthUnit, 
/**
 * Whether the shadow is inset (inside the element)
 */
inset: boolean, };
