// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxShadow } from "./BoxShadow";

/**
 * Represents a collection of box shadows, have custom `FromCss` implementation for comma-separated values.
 */
export type BoxShadows = Array<BoxShadow>;
