// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a collection of box shadows, have custom `FromCss` implementation for comma-separated values.
 */
export type BoxShadows = Array<{ 
/**
 * Whether the shadow is inset (inside the element) or outset (outside the element).
 */
inset: boolean, 
/**
 * Horizontal offset of the shadow.
 */
offsetX: LengthUnit, 
/**
 * Vertical offset of the shadow.
 */
offsetY: LengthUnit, 
/**
 * Blur radius of the shadow. Higher values create a more blurred shadow.
 */
blurRadius: LengthUnit, 
/**
 * Spread radius of the shadow. Positive values expand the shadow, negative values shrink it.
 */
spreadRadius: LengthUnit, 
/**
 * Color of the shadow.
 */
color: Color, } | string>;
