// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how the width and height of an element are calculated.
 *
 * This enum determines whether the width and height properties include padding and border, or just the content area.
 */
export type BoxSizing = "content-box" | "border-box";
