// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a box shadow with all its properties.
 *
 * Box shadows can be either outset (default) or inset, and consist of:
 * - Horizontal and vertical offsets
 * - Blur radius (optional, defaults to 0)
 * - Spread radius (optional, defaults to 0)
 * - Color (optional, defaults to transparent)
 */
export type BoxShadow = { 
/**
 * Whether the shadow is inset (inside the element) or outset (outside the element).
 */
inset: boolean, 
/**
 * Horizontal offset of the shadow.
 */
offset_x: LengthUnit, 
/**
 * Vertical offset of the shadow.
 */
offset_y: LengthUnit, 
/**
 * Blur radius of the shadow. Higher values create a more blurred shadow.
 */
blur_radius: LengthUnit, 
/**
 * Spread radius of the shadow. Positive values expand the shadow, negative values shrink it.
 */
spread_radius: LengthUnit, 
/**
 * Color of the shadow.
 */
color: Color, } | string;
