// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxShadow } from "./BoxShadow";

/**
 * Defines a box shadow for an element.
 *
 * This enum allows for flexible specification of box shadows, including
 * a single shadow or multiple shadows.
 */
export type BoxShadowInput = BoxShadow | Array<BoxShadow>;
