// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Gradient } from "./Gradient";

/**
 * Represents a color input that can be either a color or a gradient.
 */
export type ColorInput = Color | Gradient;
