// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a color with 8-bit RGBA components.
 */
export type Color = [number, number, number] | [number, number, number, number] | number | string;
