// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This enum determines the layout algorithm used for the children of a node.
 */
export type Display = "block" | "flex" | "grid" | "none";
