// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how flex items should wrap.
 *
 * This enum determines how flex items should wrap within the flex container.
 */
export type FlexWrap = "nowrap" | "wrap" | "wrap-reverse";
