// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents font weight as a numeric value.
 *
 * This wraps a u16 value that corresponds to CSS font-weight values
 * (e.g., 100 for thin, 400 for normal, 700 for bold, 900 for black).
 */
export type FontWeight = number;
