// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single font feature setting with a feature tag and value.
 */
export type FontFeatureSetting = { 
/**
 * The four-character OpenType feature tag (e.g., "liga", "kern", "smcp")
 */
tag: string, 
/**
 * The numeric value for this feature (usually 0 or 1, but can be other values)
 */
value: number, };
