// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a font family for text rendering.
 * Use only the family name (no style suffixes like "Bold", "Italic", "Regular").
 * Multi-word names are allowed (e.g., "Noto Sans") and should be provided as-is without quotes.
 */
export type FontFamily = "sans-serif" | "serif" | "monospace" | "cursive" | "fantasy" | string;
