// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents font weight as a numeric value.
 *
 * This wraps a u16 value that corresponds to CSS font-weight values.
 * Common values include 100 (thin), 200 (extra light), 300 (light),
 * 400 (normal), 500 (medium), 600 (semi bold), 700 (bold),
 * 800 (extra bold), 900 (black).
 */
export type FontWeight = number;
