// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls variable font axis values via CSS font-variation-settings property.
 *
 * This allows fine-grained control over variable font characteristics like weight,
 * width, slant, and other custom axes defined in the font.
 */
export type FontVariationSettings = string;
