// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a font family for text rendering.
 * Multi value fallback is supported.
 */
export type FontFamily = string;
