// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a single font variation setting with an axis name and value.
 */
export type FontVariationSetting = { 
/**
 * The four-character axis name (e.g., "wght", "wdth", "ital")
 */
axis: string, 
/**
 * The numeric value for this axis
 */
value: number, };
