// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontFeatureSetting } from "./FontFeatureSetting";

/**
 * Controls OpenType font features via CSS font-feature-settings property.
 *
 * This allows enabling/disabling specific typographic features in OpenType fonts
 * such as ligatures, kerning, small caps, and other advanced typography features.
 */
export type FontFeatureSettings = Array<FontFeatureSetting>;
