// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";

/**
 * Represents a single color stop in a gradient.
 */
export type GradientStop = { 
/**
 * The color of the gradient stop
 */
color: Color, 
/**
 * Position in the range [0.0, 1.0]
 */
position: number, };
