// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { StopPosition } from "./StopPosition";

/**
 * Represents a gradient stop.
 */
export type GradientStop = { 
/**
 * The color of the gradient stop.
 */
color: Color, 
/**
 * The position of the gradient stop.
 */
hint: StopPosition | null, } | StopPosition;
