// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrackSize } from "./GridTrackSize";

/**
 * A wrapper around a list of `GridTrackSize` that can also be parsed from a CSS string.
 */
export type GridTrackSizes = Array<GridTrackSize> | string;
