// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrackSize } from "./GridTrackSize";

/**
 * Represents a grid repeat track
 */
export type GridRepeatTrack = { 
/**
 * The size of the grid track
 */
size: GridTrackSize, 
/**
 * The names of the grid lines
 */
names: Array<string>, };
