// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a grid placement with serde support
 */
export type GridPlacement = null | number | number | string;
