// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrackSize } from "./GridTrackSize";

/**
 * Represents a grid repeat track
 */
export type GridRepeatTrack = { 
/**
 * The size of the grid track
 */
size: GridTrackSize, 
/**
 * The names for the line preceding this track within the repeat() clause
 */
names: Array<string>, 
/**
 * The names for the final line after the last track within the repeat() clause
 * Only set on the last track of the repeat fragment. For other tracks this is None.
 */
endNames: Array<string> | null, };
