// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the grid auto flow with serde support
 */
export type GridAutoFlow = "row" | "column" | "row dense" | "column dense";
