// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridLengthUnit } from "./GridLengthUnit";

/**
 * Represents a grid minmax()
 */
export type GridMinMaxSize = { 
/**
 * The minimum size of the grid item
 */
min: GridLengthUnit, 
/**
 * The maximum size of the grid item
 */
max: GridLengthUnit, };
