// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents `grid-template-areas` value
 *
 * Supports either a 2D matrix of area names (use "." for empty) or a CSS string value
 * like: "a a ." "b b c"
 */
export type GridTemplateAreas = Array<Array<string>> | string;
