// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridLengthUnit } from "./GridLengthUnit";
import type { GridMinMaxSize } from "./GridMinMaxSize";

/**
 * Represents a grid track size
 */
export type GridTrackSize = GridMinMaxSize | GridLengthUnit;
