// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridRepeatTrack } from "./GridRepeatTrack";
import type { GridRepetitionCount } from "./GridRepetitionCount";
import type { GridTrackSize } from "./GridTrackSize";

/**
 * Represents a track sizing function
 */
export type GridTemplateComponent = { "single": GridTrackSize } | { "repeat": [GridRepetitionCount, Array<GridRepeatTrack>] };
