// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a grid track repetition pattern
 */
export type GridRepetitionCount = "auto-fill" | "auto-fit" | number;
