// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridPlacement } from "./GridPlacement";

/**
 * Represents a grid line placement with serde support
 */
export type GridLine = { 
/**
 * The start line placement
 */
start: GridPlacement | null, 
/**
 * The end line placement
 */
end: GridPlacement | null, };
