// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTemplateComponent } from "./GridTemplateComponent";

/**
 * A transparent wrapper around a list of `GridTemplateComponent`.
 *
 * This exists to provide a distinct type for template component lists while
 * preserving JSON compatibility (serialized as a plain array) and clean TS types.
 */
export type GridTemplateComponents = Array<GridTemplateComponent> | string;
