// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how images should be scaled when rendered.
 */
export type ImageScalingAlgorithm = "auto" | "smooth" | "pixelated";
