// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { FontFamily } from "./FontFamily";
import type { FontWeight } from "./FontWeight";
import type { ImageScalingAlgorithm } from "./ImageScalingAlgorithm";
import type { LengthUnit } from "./LengthUnit";
import type { LinearGradientOrColor } from "./LinearGradientOrColor";
import type { Sides } from "./Sides";
import type { TextAlign } from "./TextAlign";
import type { TextOverflow } from "./TextOverflow";

/**
 * Style properties that can be inherited by child elements.
 */
export type InheritableStyle = { 
/**
 * How text should be overflowed.
 */
text_overflow?: TextOverflow, 
/**
 * Color of the element's border.
 */
border_color?: Color, 
/**
 * Text color for child text elements.
 */
color?: LinearGradientOrColor, 
/**
 * Font size for text rendering.
 */
font_size?: LengthUnit, 
/**
 * Font family name for text rendering.
 */
font_family?: FontFamily, 
/**
 * Line height for text spacing.
 */
line_height?: LengthUnit, 
/**
 * Font weight for text rendering.
 */
font_weight?: FontWeight, 
/**
 * Maximum number of lines for text before truncation.
 */
line_clamp?: number, 
/**
 * Shorthand border radius (top, right, bottom, left).
 */
border_radius?: Sides<LengthUnit>, 
/**
 * Longhand: top border radius. Overrides `border_radius` top value.
 */
border_radius_top?: LengthUnit, 
/**
 * Longhand: right border radius. Overrides `border_radius` right value.
 */
border_radius_right?: LengthUnit, 
/**
 * Longhand: bottom border radius. Overrides `border_radius` bottom value.
 */
border_radius_bottom?: LengthUnit, 
/**
 * Longhand: left border radius. Overrides `border_radius` left value.
 */
border_radius_left?: LengthUnit, 
/**
 * Text alignment within the element.
 */
text_align?: TextAlign, 
/**
 * Additional spacing between characters in text.
 */
letter_spacing?: LengthUnit, 
/**
 * Controls how images are scaled when rendered.
 */
image_rendering?: ImageScalingAlgorithm, };
