// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoxSizing } from "./BoxSizing";
import type { Color } from "./Color";
import type { FontFamily } from "./FontFamily";
import type { FontWeight } from "./FontWeight";
import type { ImageScalingAlgorithm } from "./ImageScalingAlgorithm";
import type { LengthUnit } from "./LengthUnit";
import type { LinearGradientOrColor } from "./LinearGradientOrColor";
import type { Sides } from "./Sides";
import type { TextAlign } from "./TextAlign";
import type { TextOverflow } from "./TextOverflow";
import type { TextStyle } from "./TextStyle";
import type { TextTransform } from "./TextTransform";

/**
 * Style properties that can be inherited by child elements.
 */
export type InheritableStyle = { 
/**
 * How the width and height of an element are calculated.
 */
boxSizing?: BoxSizing, 
/**
 * How text should be overflowed.
 */
textOverflow?: TextOverflow, 
/**
 * Controls text case transformation when rendering.
 */
textTransform?: TextTransform, 
/**
 * Font slant style (normal, italic, oblique).
 */
textStyle?: TextStyle, 
/**
 * Color of the element's border.
 */
borderColor?: Color, 
/**
 * Text color for child text elements.
 */
color?: LinearGradientOrColor, 
/**
 * Font size for text rendering.
 */
fontSize?: LengthUnit, 
/**
 * Font family name for text rendering.
 */
fontFamily?: FontFamily, 
/**
 * Line height for text spacing.
 */
lineHeight?: LengthUnit, 
/**
 * Font weight for text rendering.
 */
fontWeight?: FontWeight, 
/**
 * Maximum number of lines for text before truncation.
 */
lineClamp?: number, 
/**
 * Shorthand border radius (top, right, bottom, left).
 */
borderRadius?: Sides<LengthUnit>, 
/**
 * Longhand: top border radius. Overrides `border_radius` top value.
 */
borderRadiusTop?: LengthUnit, 
/**
 * Longhand: right border radius. Overrides `border_radius` right value.
 */
borderRadiusRight?: LengthUnit, 
/**
 * Longhand: bottom border radius. Overrides `border_radius` bottom value.
 */
borderRadiusBottom?: LengthUnit, 
/**
 * Longhand: left border radius. Overrides `border_radius` left value.
 */
borderRadiusLeft?: LengthUnit, 
/**
 * Text alignment within the element.
 */
textAlign?: TextAlign, 
/**
 * Additional spacing between characters in text.
 */
letterSpacing?: LengthUnit, 
/**
 * Controls how images are scaled when rendered.
 */
imageRendering?: ImageScalingAlgorithm, };
