// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how flex items are aligned along the main axis.
 *
 * This enum determines how space is distributed between and around flex items
 * along the main axis of the flex container.
 */
export type JustifyContent =
  | "start"
  | "end"
  | "flex-start"
  | "flex-end"
  | "center"
  | "stretch"
  | "space-between"
  | "space-evenly"
  | "space-around";
