// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a value that can be a specific length, percentage, or automatic.
 *
 * This corresponds to CSS values that can be specified as pixels, percentages,
 * or the 'auto' keyword for automatic sizing.
 */
export type LengthUnit = "auto" | { "percentage": number } | { "rem": number } | { "em": number } | { "vh": number } | { "vw": number } | number | string;
