// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Angle } from "./Angle";
import type { GradientStop } from "./GradientStop";

/**
 * Represents a linear gradient.
 */
export type LinearGradient = { 
/**
 * The angle of the gradient.
 */
angle: Angle, 
/**
 * The steps of the gradient.
 */
stops: Array<GradientStop>, } | string;
