// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a line height value, number value is parsed as em.
 */
export type LineHeight = number | string | LengthUnit;
