// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinearGradient } from "./LinearGradient";

/**
 * A collection of linear gradients.
 */
export type LinearGradients = Array<LinearGradient> | string;
