// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LinearGradient } from "./LinearGradient";

/**
 * Represents either a linear gradient or a solid color.
 */
export type LinearGradientOrColor = LinearGradient | Color;
