// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Procedural noise gradient that generates organic, natural-looking patterns using fractal Brownian motion.
 * This creates dynamic textures that can be used as backgrounds or overlays with customizable parameters
 * for controlling the noise characteristics and visual appearance.
 */
export type NoiseV1 = { 
/**
 * Controls the scale of the noise pattern. Higher values create finer, more detailed patterns
 */
frequency: number | null, 
/**
 * Random seed value that determines the unique noise pattern generated
 */
seed: number | null, 
/**
 * Number of noise layers combined to create complex patterns. More octaves add detail
 */
octaves: number | null, 
/**
 * Controls how much each octave contributes to the final pattern. Lower values create smoother patterns
 */
persistence: number | null, 
/**
 * Controls the frequency multiplier between octaves. Higher values create more varied patterns
 */
lacunarity: number | null, };
