// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how an image should be resized to fit its container.
 *
 * Similar to CSS object-fit property.
 */
export type ObjectFit = "fill" | "contain" | "cover" | "scale-down" | "none";
