// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls how text should be overflowed.
 */
export type OverflowWrap = "normal" | "anywhere" | "break-word";
