// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";
import type { PositionKeywordX } from "./PositionKeywordX";
import type { PositionKeywordY } from "./PositionKeywordY";

/**
 * A single `background-position` component for an axis.
 */
export type PositionComponent =
  | { "keyword-x": PositionKeywordX }
  | { "keyword-y": PositionKeywordY }
  | { length: LengthUnit };
