// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines the positioning method for an element.
 *
 * This enum determines how an element is positioned within its containing element.
 */
export type Position = "relative" | "absolute";
