// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Horizontal keywords for `background-position`.
 */
export type PositionKeywordX = "left" | "center" | "right";
