// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Vertical keywords for `background-position`.
 */
export type PositionKeywordY = "top" | "center" | "bottom";
