// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported size keywords for radial gradients
 */
export type RadialSize =
  | "closest-side"
  | "farthest-side"
  | "closest-corner"
  | "farthest-corner";
