// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported shapes for radial gradients
 */
export type RadialShape = "circle" | "ellipse";
