// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents the values for the four sides of a box (top, right, bottom, left).
 */
export type Sides<T> = string | [T, T, T, T] | [T, T] | T;
