// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents values that can be applied to all sides of an element.
 *
 * This enum allows for flexible specification of values like padding, margin,
 * or border sizes using either a single value for all sides, separate values
 * for vertical/horizontal axes, or individual values for each side.
 */
export type SidesValue<T> = T | [T, T] | [T, T, T, T];
