// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a gradient stop position.
 * If a percentage or number (0.0-1.0) is provided, it is treated as a percentage.
 */
export type StopPosition = LengthUnit | string;
