// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextShadow } from "./TextShadow";

/**
 * Represents a collection of text shadows; has custom `FromCss` implementation for comma-separated values.
 */
export type TextShadows = Array<TextShadow> | string;
