// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls the slant (italic/oblique) of text rendering.
 */
export type TextStyle = "normal" | "italic" | "oblique";
