// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a text shadow with all its properties.
 */
export type TextShadow =
  | {
      /**
       * Horizontal offset of the shadow.
       */
      offsetX: LengthUnit;
      /**
       * Vertical offset of the shadow.
       */
      offsetY: LengthUnit;
      /**
       * Blur radius of the shadow. Higher values create a more blurred shadow.
       */
      blurRadius: LengthUnit;
      /**
       * Color of the shadow.
       */
      color: Color;
    }
  | string;
