// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { LengthUnit } from "./LengthUnit";

/**
 * Parsed `text-stroke` value.
 *
 * `color` is optional; when absent the element's `color` property should be used.
 */
export type TextStroke = { width: LengthUnit, color: Color | null, } | string;
