// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls text case transformation when rendering.
 */
export type TextTransform = "none" | "uppercase" | "lowercase" | "capitalize";
