// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Defines how text should be overflowed.
 *
 * This enum determines how text should be handled when it exceeds the container width.
 */
export type TextOverflow = "ellipsis" | "clip";
