// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GridTrackRepetition } from "./GridTrackRepetition";
import type { GridTrackSize } from "./GridTrackSize";

/**
 * Represents a track sizing function
 */
export type TrackSizingFunction = { "single": GridTrackSize } | { "repeat": [GridTrackRepetition, Array<GridTrackSize>] };
