// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Transform } from "./Transform";

/**
 * A collection of transform operations that can be applied together
 */
export type Transforms = Array<Transform> | string;
