// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Affine } from "./Affine";
import type { Angle } from "./Angle";
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a single CSS transform operation
 */
export type Transform = { "translate": [LengthUnit, LengthUnit] } | { "scale": [number, number] } | { "rotate": Angle } | { "skew": [Angle, Angle] } | { "matrix": Affine };
