// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls how text should be broken at word boundaries.
 *
 * Corresponds to CSS word-break property.
 */
export type WordBreak = "normal" | "break-all" | "keep-all";
